//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helloserve.com.Shedding.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authority
    {
        public Authority()
        {
            this.Areas = new HashSet<Area>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ClassType { get; set; }
        public string DataUrl { get; set; }
        public string StatusUrl { get; set; }
    
        public virtual ICollection<Area> Areas { get; set; }
    }
}
