//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helloserve.com.Shedding.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoadShedEntities : DbContext
    {
        public LoadShedEntities()
            : base("name=LoadShedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Authority> Authorities { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<SheddingStage> SheddingStages { get; set; }
        public virtual DbSet<UserArea> UserAreas { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserPushRegistration> UserPushRegistrations { get; set; }
        public virtual DbSet<ScheduleCalendar> ScheduleCalendars { get; set; }
    }
}
