//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helloserve.com.Shedding.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.ScheduleCalendars = new HashSet<ScheduleCalendar>();
        }
    
        public int Id { get; set; }
        public int AreaId { get; set; }
        public int SheddingStageId { get; set; }
        public Nullable<int> DayOfMonth { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
        public Nullable<decimal> StartTime { get; set; }
        public Nullable<decimal> EndTime { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual SheddingStage SheddingStage { get; set; }
        public virtual ICollection<ScheduleCalendar> ScheduleCalendars { get; set; }
    }
}
