//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helloserve.com.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeatureMedia
    {
        public int FeatureMediaID { get; set; }
        public int FeatureID { get; set; }
        public int MediaID { get; set; }
    
        public virtual Feature Feature { get; set; }
        public virtual Media Media { get; set; }
    }
}
