//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helloserve.com.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        public Feature()
        {
            this.Downloadables = new HashSet<Downloadable>();
            this.FeatureMedias = new HashSet<FeatureMedia>();
            this.FeatureRequirements = new HashSet<FeatureRequirement>();
            this.News = new HashSet<News>();
            this.RelatedLinks = new HashSet<RelatedLink>();
            this.SellingPoints = new HashSet<SellingPoint>();
        }
    
        public int FeatureID { get; set; }
        public string Name { get; set; }
        public bool IsMainFeature { get; set; }
        public string Description { get; set; }
        public string ExtendedDescription { get; set; }
        public string MediaFolder { get; set; }
        public Nullable<int> HeaderImageID { get; set; }
        public string Subdomain { get; set; }
        public string CustomPage { get; set; }
        public string IndieDBLink { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Color { get; set; }
        public string BackgroundColor { get; set; }
    
        public virtual ICollection<Downloadable> Downloadables { get; set; }
        public virtual ICollection<FeatureMedia> FeatureMedias { get; set; }
        public virtual ICollection<FeatureRequirement> FeatureRequirements { get; set; }
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<RelatedLink> RelatedLinks { get; set; }
        public virtual ICollection<SellingPoint> SellingPoints { get; set; }
    }
}
