//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helloserve.com.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForumCategory
    {
        public ForumCategory()
        {
            this.ForumTopics = new HashSet<ForumTopic>();
        }
    
        public int ForumCategoryID { get; set; }
        public int ForumID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int SortOrder { get; set; }
    
        public virtual Forum Forum { get; set; }
        public virtual ICollection<ForumTopic> ForumTopics { get; set; }
    }
}
