//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helloserve.com.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class helloserveEntities : DbContext
    {
        public helloserveEntities()
            : base("name=helloserveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Downloadable> Downloadables { get; set; }
        public virtual DbSet<Error> Errors { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<FeatureMedia> FeatureMedias { get; set; }
        public virtual DbSet<FeatureRequirement> FeatureRequirements { get; set; }
        public virtual DbSet<Forum> Fora { get; set; }
        public virtual DbSet<ForumCategory> ForumCategories { get; set; }
        public virtual DbSet<ForumPost> ForumPosts { get; set; }
        public virtual DbSet<ForumTopic> ForumTopics { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Media> Medias { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<RelatedLink> RelatedLinks { get; set; }
        public virtual DbSet<Requirement> Requirements { get; set; }
        public virtual DbSet<SellingPoint> SellingPoints { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
