//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helloserve.com.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int LogID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public string Category { get; set; }
        public string Message { get; set; }
        public string Source { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> FeatureID { get; set; }
        public Nullable<int> NewsID { get; set; }
        public Nullable<int> MediaID { get; set; }
        public Nullable<int> DownloadID { get; set; }
        public Nullable<System.DateTime> Initiated { get; set; }
        public Nullable<decimal> ElapsedSeconds { get; set; }
    }
}
