//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helloserve.com.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medium
    {
        public Medium()
        {
            this.FeatureMedias = new HashSet<FeatureMedia>();
            this.News = new HashSet<News>();
        }
    
        public int MediaID { get; set; }
        public int MediaType { get; set; }
        public string FileName { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
        public string Location { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual ICollection<FeatureMedia> FeatureMedias { get; set; }
        public virtual ICollection<News> News { get; set; }
    }
}
