//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helloserve.com.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsID { get; set; }
        public Nullable<int> FeatureID { get; set; }
        public string Title { get; set; }
        public string Cut { get; set; }
        public string Post { get; set; }
        public Nullable<int> HeaderImageID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Feature Feature { get; set; }
        public virtual Medium Medium { get; set; }
    }
}
