//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helloserve.com.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement
    {
        public Requirement()
        {
            this.FeatureRequirements = new HashSet<FeatureRequirement>();
        }
    
        public int RequirementID { get; set; }
        public string Description { get; set; }
        public string Link { get; set; }
        public byte[] Icon { get; set; }
    
        public virtual ICollection<FeatureRequirement> FeatureRequirements { get; set; }
    }
}
