//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace helloserve.com.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ForumPosts = new HashSet<ForumPost>();
            this.ForumTopics = new HashSet<ForumTopic>();
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public byte[] Password { get; set; }
        public string EmailAddress { get; set; }
        public bool ReceiveUpdates { get; set; }
        public bool Administrator { get; set; }
        public System.Guid ActivationToken { get; set; }
        public bool Activated { get; set; }
    
        public virtual ICollection<ForumPost> ForumPosts { get; set; }
        public virtual ICollection<ForumTopic> ForumTopics { get; set; }
    }
}
