IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = N'Blogs')
CREATE TABLE dbo.[Blogs]
(
	[Key] NVARCHAR(250) NOT NULL,
	Title NVARCHAR(250) NULL,
	Content NVARCHAR(MAX) NULL,
	IsPublished BIT NOT NULL,
	PublishDate DATETIME NULL,
	CONSTRAINT PK_Blogs PRIMARY KEY NONCLUSTERED ([Key]) ON [PRIMARY]
) ON [PRIMARY]
